#!/usr/bin/python
__version__ = "0.1"
__author__ = "Saij"

import sys, os, stat
import argparse, logging, asyncore, time
import wpactrl

from pybtapi import BTServer, BTError

class MainClass(argparse.ArgumentParser):
    def __init__(self, *args, **kwargs):
        super(MainClass, self).__init__(*args, **kwargs)

        self.add_argument("-v", "--version", action = "store_true", help = "Print version info and exit")
        self.add_argument("-d", "--debug", action = "store_true", help = "Enables debug output")
        self.add_argument("--serial", action = "store_true", help = "Change UUID to serial communication UUID (only in debug mode)")
        self.add_argument("--ctrl-path", action = "store", help = "Path of wpa_supplicant control sockets", default = "/var/run/wpa_supplicant")
        
        self.add_argument("-i", "--interface", action = "store", help = "Interface to configure using wpa_supplicant", required = True)
        
        self.args = {}


    def process(self):
        self.args = vars(self.parse_args())
        if self.args["version"]:
            print("rpy-bt-wifi-config v%s" % __version__)
            sys.exit(0)

        uuid = "3FBBC3A8-627F-4A29-B76C-5CB836BD37A3"
        log_level = logging.INFO

        if self.args["debug"]:
            log_level = logging.DEBUG
            if self.args["serial"]:
                uuid = "00001101-0000-1000-8000-00805F9B34FB"

        logging.basicConfig(level = log_level, format = "%(asctime)s - %(levelname)s - %(message)s")

        print("Raspberry PI Bluetooth WiFi Config\n")

        # Setup wpa_supplicant control interface
        socket = os.path.join(self.args["ctrl_path"], self.args["interface"])
        if not os.path.exists(socket):
            logging.error("Socket %s could not be found!" % socket)
            sys.exit(1)

        if not stat.S_ISSOCK(os.stat(socket).st_mode):
            logging.error("Path %s is not a socket!" % socket)
            sys.exit(1)

        self.wpa = wpactrl.WPACtrl(socket)

        logging.info("Connected to wpa_supplicant through control socket")
        
        # Setup BTServer
        self.btserver = BTServer(uuid = uuid, service_name = "RPy BT WiFi Config")
        
        self.btserver.add_command("scan", self._cmd_scan)
        self.btserver.add_command("scan_result", self._cmd_scan_result)
        self.btserver.add_command("status", self._cmd_status)
        self.btserver.add_command("list_networks", self._cmd_list_networks)
        self.btserver.add_command("network_get", self._cmd_network_get)
        self.btserver.add_command("network_set", self._cmd_network_set)

        try:
            # Start loop
            asyncore.loop()
        except KeyboardInterrupt:
            print "Exiting\n"
            sys.exit(0)

        return True

    def _cmd_network_set(self, handler, network, variable, value):
        try:
            ret = self.wpa.request("SET_NETWORK %s %s %s" % (network, variable, value)).strip()
            logging.debug("SET_NETWORK %s %s %s returns:\n%s" % (network, variable, value, ret))

            if ret == "FAIL":
                handler.send_error(BTError.ERR_UNKNOWN, "Error setting property")
                return

            handler.send_success();
        except wpactrl.error as e:
            handler.send_error(BTError.ERR_UNKNOWN, e)
            pass

    def _cmd_network_get(self, handler, network, variable):
        try:
            ret = self.wpa.request("GET_NETWORK %s %s" % (network, variable)).strip()
            logging.debug("GET_NETWORK %s %s returns:\n%s" % (network, variable, ret))

            if ret == "FAIL":
                handler.send_error(BTError.ERR_UNKNOWN, "Unknown property for this network")
                return

            handler.send_success(ret)
        except wpactrl.error as e:
            handler.send_error(BTError.ERR_UNKNOWN, e)
            pass

    def _cmd_list_networks(self, handler):
        try:
            ret = self.wpa.request("LIST_NETWORKS")
            logging.debug("LIST_NETWORKS returns:\n%s" % ret)

            ret_list = ret.strip().split("\n")
            # remove line with headers
            del ret_list[0]

            nets = {}
            for line in ret_list:
                net_dict = dict(zip(("net_id", "ssid", "bssid", "flags"), line.strip().split("\t")))
                nets[net_dict["net_id"]] = net_dict

            handler.send_success(nets)
        except wpactrl.error as e:
            handler.send_error(BTError.ERR_UNKNOWN, e)
            pass

    def _cmd_status(self, handler, verbose = False):
        try:
            if verbose:
                ret = self.wpa.request("STATUS-VERBOSE")
            else:
                ret = self.wpa.request("STATUS")

            logging.debug("STATUS returns:\n%s" % ret)

            handler.send_success(dict((key.strip(), value.strip()) for key, value in (line.split("=") for line in ret.strip().split("\n"))))
        except wpactrl.error as e:
            handler.send_error(BTError.ERR_UNKNOWN, e)
            pass

    def _cmd_scan_result(self, handler):
        try:
            ret = self.wpa.scanresults()
            logging.debug("SCAN RESULT returns:\n%s" % ret)

            # Parse scan result and extract
            bss_list = []
            for no, bss in enumerate(ret):
                bss_dict = dict((key.strip(), value.strip()) for key, value in (line.split("=") for line in bss.strip().split("\n")))
                bss_list.append(bss_dict)

            handler.send_success(data = bss_list)
        except wpactrl.error as e:
            handler.send_error(BTError.ERR_UNKNOWN, e)
            pass

    def _cmd_scan(self, handler, wait = 10):
        try:
            ret = self.wpa.request("SCAN")
            logging.debug("SCAN returns:\n%s" % ret)
            if ret.strip() != "OK":
                handler.send_error(BTError.ERR_UNKNOWN, "Error requesting scan: %s" % ret)
                return;

            if wait == 0:
                handler.send_success()
                return

            logging.debug("Waiting for scan result %d seconds" % wait)
            time.sleep(wait)

            self._cmd_scan_result(handler = handler)
        except wpactrl.error as e:
            handler.send_error(BTError.ERR_UNKNOWN, e)
            pass

# Main function
if __name__ == "__main__":
    parser = MainClass()
    if (not parser.process()):
        parser.print_help()